### ISSUE TITLE
Any plan for model runtimes?

### ISSUE THREAD

**Issue by umutphp** [seymahandekli/git-gen#2]
Hi @seymahandekli ,

Many thanks for this great tool and making it open source. It was an idea on my list but you did it :).

I wonder if you have plan to add support to use models locally via runtimes such as Ollama or Onnx.

**Comment by seymahandekli** [comment]
Hi @umutphp,

Thank you for the feedback!

I would consider adding it as soon as I researched how to work with other models like you’ve mentioned.
